# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Code\Python\Arduino-PyInterface-MRS\gui\ui\portWindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(300, 260)
        MainWindow.setMinimumSize(QtCore.QSize(300, 260))
        MainWindow.setMaximumSize(QtCore.QSize(300, 260))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.port = QtWidgets.QComboBox(self.centralwidget)
        self.port.setMinimumSize(QtCore.QSize(0, 0))
        self.port.setObjectName("port")
        self.horizontalLayout.addWidget(self.port)
        self.lPort = QtWidgets.QLabel(self.centralwidget)
        self.lPort.setMaximumSize(QtCore.QSize(400, 400))
        self.lPort.setAlignment(QtCore.Qt.AlignCenter)
        self.lPort.setObjectName("lPort")
        self.horizontalLayout.addWidget(self.lPort)
        self.verticalLayout_2.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.speed = QtWidgets.QComboBox(self.centralwidget)
        self.speed.setMinimumSize(QtCore.QSize(0, 0))
        self.speed.setObjectName("speed")
        self.horizontalLayout_2.addWidget(self.speed)
        self.lSpeed = QtWidgets.QLabel(self.centralwidget)
        self.lSpeed.setMaximumSize(QtCore.QSize(400, 16777215))
        self.lSpeed.setAlignment(QtCore.Qt.AlignCenter)
        self.lSpeed.setObjectName("lSpeed")
        self.horizontalLayout_2.addWidget(self.lSpeed)
        self.verticalLayout_2.addLayout(self.horizontalLayout_2)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem)
        self.progressBar = QtWidgets.QProgressBar(self.centralwidget)
        self.progressBar.setProperty("value", 24)
        self.progressBar.setObjectName("progressBar")
        self.verticalLayout_2.addWidget(self.progressBar)
        self.connect = QtWidgets.QPushButton(self.centralwidget)
        self.connect.setObjectName("connect")
        self.verticalLayout_2.addWidget(self.connect)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.OK = QtWidgets.QPushButton(self.centralwidget)
        self.OK.setMinimumSize(QtCore.QSize(0, 50))
        self.OK.setObjectName("OK")
        self.horizontalLayout_3.addWidget(self.OK)
        self.Cancel = QtWidgets.QPushButton(self.centralwidget)
        self.Cancel.setMinimumSize(QtCore.QSize(0, 50))
        self.Cancel.setObjectName("Cancel")
        self.horizontalLayout_3.addWidget(self.Cancel)
        self.verticalLayout_2.addLayout(self.horizontalLayout_3)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 300, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.lPort.setText(_translate("MainWindow", "Choice available port"))
        self.lSpeed.setText(_translate("MainWindow", "Choice speed of port"))
        self.connect.setText(_translate("MainWindow", "Connect"))
        self.OK.setText(_translate("MainWindow", "OK"))
        self.Cancel.setText(_translate("MainWindow", "Cancel"))
